const icons = {
  home: {
    filled: require("../assets/images/home-filled.png"),
    outlined: require("../assets/images/home-outlined.png"),
  },
  add: require("../assets/images/add.png"),
  avatar: require("../assets/images/avatar.png"),
  collection: require("../assets/images/add-folder.png"),
  backspace: require("../assets/images/backspace.png"),
  budgets: {
    filled: require("../assets/images/budget-filled.png"),
    outlined: require("../assets/images/budget-outlined.png"),
  },
  camera: require("../assets/images/camera.png"),
  check: require("../assets/images/check.png"),
  checkbox: {
    checked: require("../assets/images/checkbox-checked.png"),
    unchecked: require("../assets/images/checkbox-unchecked.png"),
  },
  chevron: require("../assets/images/chevron.png"),
  copy: require("../assets/images/copy.png"),
  date: require("../assets/images/date.png"),
  delete: require("../assets/images/delete.png"),
  dictionary: require("../assets/images/dictionary.png"),
  download: require("../assets/images/download.png"),
  edit: require("../assets/images/edit.png"),
  error: require("../assets/images/error.png"),
  excel: require("../assets/images/excel.png"),
  expenses: {
    filled: require("../assets/images/expenses-filled.png"),
    outlined: require("../assets/images/expenses-outlined.png"),
  },
  export: require("../assets/images/export.png"),
  folder: require("../assets/images/folder.png"),
  form: require("../assets/images/form.png"),
  help: require("../assets/images/question.png"),
  history: require("../assets/images/history.png"),
  image: require("../assets/images/image.png"),
  import: require("../assets/images/import.png"),
  info: require("../assets/images/info.png"),
  keyword: require("../assets/images/keyword.png"),
  link: require("../assets/images/link.png"),
  lock: require("../assets/images/lock.png"),
  logo: require("../assets/images/icon.png"),
  logout: require("../assets/images/logout.png"),
  menu: require("../assets/images/menu.png"),
  money: require("../assets/images/money.png"),
  move: require("../assets/images/move.png"),
  notification: require("../assets/images/notification.png"),
  options: require("../assets/images/options.png"),
  pieChart: require("../assets/images/pie-chart.png"),
  radio: {
    checked: require("../assets/images/radio-checked.png"),
    unchecked: require("../assets/images/radio-unchecked.png"),
  },
  rating: {
    love: {
      enabled: require("../assets/images/love.png"),
      disabled: require("../assets/images/love-disabled.png"),
    },
    hate: {
      enabled: require("../assets/images/hate.png"),
      disabled: require("../assets/images/hate-disabled.png"),
    },
    neutral: {
      enabled: require("../assets/images/neutral.png"),
      disabled: require("../assets/images/neutral-disabled.png"),
    },
  },
  receipt: require("../assets/images/receipt.png"),
  report: require("../assets/images/report.png"),
  restore: require("../assets/images/restore.png"),
  arrow: require("../assets/images/arrow.png"),
  search: require("../assets/images/search.png"),
  select: require("../assets/images/select.png"),
  send: require("../assets/images/send.png"),
  settings: require("../assets/images/settings.png"),
  sms: require("../assets/images/sms.png"),
  insights: {
    filled: require("../assets/images/statistics-filled.png"),
    outlined: require("../assets/images/statistics-outlined.png"),
  },
  pdf: require("../assets/images/pdf.png"),
  success: require("../assets/images/success.png"),
  warning: require("../assets/images/warning.png"),
  zip: require("../assets/images/zip.png"),
};

export default icons;
